# Quiz

var whatIsIt string secret := "CYtZBsWZaZliYZocWLZlXuZZYWYeYXZsXeZXtXWpXeRYYYd!ZnYeWXoYXasnX,WXWrWPoAdWesnciGenWr"

📍 Hint : Sometimes the high frequency of characters are meaningless. You may have to zigzag walk to reach your destination.

In [1]:
txt = 'CYtZBsWZaZliYZocWLZlXuZZYWYeYXZsXeZXtXWpXeRYYYd!ZnYeWXoYXasnX,WXWrWPoAdWesnciGenWr'

In [2]:
len(txt)

82

In [3]:
# https://github.com/piruin/th-en-keyboard

x = """ๅ	1
+	!
๑	@
/	2
-	3
๒	#
ภ	4
๓	$
ถ	5
๔	%
ุ	6
ู	^
ึ	7
฿	&
ค	8
๕	*
ต	9
๖	(
จ	0
๗	)
ข	-
๘	_
ช	=
๙	+
ๆ	q
๐	Q
ไ	w
"	W
ำ	e
ฎ	E
พ	r
ฑ	R
ะ	t
ธ	T
ั	y
ํ	Y
ี	u
๊	U
ร	i
ณ	I
น	o
ฯ	O
ย	p
ญ	P
บ	[
ฐ	{
ล	]
`	`
ฃ	\\
ฅ	`
ฟ	a
ฤ	A
ห	s
ฆ	S
ก	d
ฏ	D
ด	f
โ	F
เ	g
ฌ	G
้	h
็	H
่	j
๋	J
า	k
ษ	K
ส	l
ศ	L
ว	;
ซ	:
ง	'
.	"
ผ	z
(	Z
ป	x
)	X
แ	c
ฉ	C
อ	v
ฮ	V
ิ	b
ฺ	B
ท	n
์	N
ท	m
?	M
ม	,
ฒ	<
ใ	.
ฬ	>
ฝ	/
ฦ	?"""

In [4]:
map_keyboard = {e.split('\t')[1]: e.split('\t')[0] for e in x.split('\n')}

In [5]:
from collections import Counter
counts = Counter(list(txt))
counts = dict(counts)

dict_c = {k: [map_keyboard[k], v] for k, v in counts.items()}

dict(sorted(dict_c.items(), key=lambda item: item[1][1], reverse = True))

{'Y': ['ํ', 10],
 'Z': ['(', 10],
 'W': ['"', 10],
 'X': [')', 10],
 'e': ['ำ', 6],
 's': ['ห', 4],
 'n': ['ท', 4],
 'o': ['น', 3],
 't': ['ะ', 2],
 'a': ['ฟ', 2],
 'l': ['ส', 2],
 'i': ['ร', 2],
 'c': ['แ', 2],
 'd': ['ก', 2],
 'r': ['พ', 2],
 'C': ['ฉ', 1],
 'B': ['ฺ', 1],
 'L': ['ศ', 1],
 'u': ['ี', 1],
 'p': ['ย', 1],
 'R': ['ฑ', 1],
 '!': ['+', 1],
 ',': ['ม', 1],
 'P': ['ญ', 1],
 'A': ['ฤ', 1],
 'G': ['ฌ', 1]}

"WXYZ" high frequency -> meaningless

in Thai Keyboard "WXYZ" = ")ํ(." -> meaningless

so, it's something related to Thai Word?

In [6]:
import numpy as np
import pandas as pd

# Method 1: Zigzag Scan

In [7]:
txt2 = ''
txt3 = ''
txt4 = ''
txt5 = ''
for c in txt:
    txt2 = txt2 + c if c not in 'WXYZ' else txt2
    txt3 = txt3 + map_keyboard[c] if c not in 'WXYZ' else txt3
    txt4 = txt4 + map_keyboard[c]
    txt5 = txt5 + c if c not in 'WXYZ' else txt5 + '_'
    
print("txt: ", txt)
print("txt2: ", txt2)
print("txt3: ", txt3)
print("txt4: ", txt4)
print("txt5: ", txt5)

txt:  CYtZBsWZaZliYZocWLZlXuZZYWYeYXZsXeZXtXWpXeRYYYd!ZnYeWXoYXasnX,WXWrWPoAdWesnciGenWr
txt2:  CtBsaliocLluesetpeRd!neoasn,rPoAdesnciGenr
txt3:  ฉะฺหฟสรนแศสีำหำะยำฑก+ทำนฟหทมพญนฤกำหทแรฌำทพ
txt4:  ฉํะ(ฺห"(ฟ(สรํ(นแ"ศ(ส)ี((ํ"ํำํ)(ห)ำ()ะ)"ย)ำฑํํํก+(ทํำ")นํ)ฟหท)ม")"พ"ญนฤก"ำหทแรฌำท"พ
txt5:  C_t_Bs__a_li__oc_L_l_u_____e___s_e__t__p_eR___d!_n_e__o__asn_,___r_PoAd_esnciGen_r


in thai words we have ฑ, ฤ so it's hard to make a sentence

In [8]:
def zigzag_txt(s, matrix_loc, map_thai = False, ban = 'WXYZ'):
    a, b = matrix_loc.shape
    m = np.zeros((a, b), dtype="object")
    for i in range(a):
        for j in range(b):
            if matrix_loc[i, j] == ' ':
                m[i, j] = " "
                continue

            if len(s) >= int(matrix_loc[i, j]):

                c = s[int(matrix_loc[i, j]) - 1]

                if c in ban:
                    c = ' '

                if map_thai:
                    m[i, j] = map_keyboard.get(c, ' ')
                else:
                    m[i, j] = c

            else:
                m[i, j] = " "
    
    return m

In [9]:
def to_word(m, include_blank=True):
    temp_txt = ''
    for lc in m:
        for c in lc:
            if include_blank:
                temp_txt = temp_txt + c
            else:
                temp_txt = temp_txt + c if c != ' ' else temp_txt
    return temp_txt

In [12]:
def create_zigzag_index(n):
    m = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            m[i, j] = (2*(np.floor((i+1)/2))*np.floor((i+1)/2) + np.ceil((i-1)/2) + 1)\
                        + 2*(np.floor((j+(i%2))/2)+((i+1)%2))*np.floor((j+(i%2))/2) + np.ceil((j-(i%2))/2)*(2*i+1)
    return m


def create_zigzag_index2(n):
    return np.array([list(range(i*n, n*(i+1))) if i%2==0 else list(range(n*(i+1)-1, i*n-1, -1)) for i in range(n)]) + 1


def create_zigzag_index3(n):
    matrix = np.array(range(n**2)).reshape(n,n) + 1
    c_list = []
    # printing elements above and on
    # second diagonal
    for k in range(n):
        # traversing downwards starting
        # from first row
        row = 0
        col = k
        while (col >= 0):
#             print(matrix[row][col],end = " ")
            c_list.append(matrix[row][col])
            row += 1
            col -= 1
 
    # printing elements below second
    # diagonal
    for j in range(1, n):
        # traversing downwards starting
        # from last column
        col = n - 1
        row = j
        while (row < n):
#             print(matrix[row][col],end = " ")
            c_list.append(matrix[row][col])
            row += 1
            col -= 1
    
    k = np.array(range(n**2)).reshape(n,n) + 1
    mm = {e: i for i, e in enumerate(c_list)}
    matrix = np.array([[mm[e]+1 for e in l1] for l1 in k])
    
#     return np.array(c_list).reshape(n, n)

    return matrix


def create_zigzag_index4(n):
    matrix = np.array(range(n**2)).reshape(n,n) + 1
    c_list = []
    # printing elements above and on
    # second diagonal
    for k in range(n):
        # traversing downwards starting
        # from first row
        row = 0
        col = k
        while (col >= 0):
#             print(matrix[row][col],end = " ")
            c_list.append(matrix[row][col])
            row += 1
            col -= 1
 
    # printing elements below second
    # diagonal
    for j in range(1, n):
        # traversing downwards starting
        # from last column
        col = n - 1
        row = j
        while (row < n):
#             print(matrix[row][col],end = " ")
            c_list.append(matrix[row][col])
            row += 1
            col -= 1
            
    return np.array(c_list).reshape(n, n)


def create_zigzag_index5(n):
    a = np.array(range(n**2)).reshape(n,n) + 1
    c_list = np.concatenate([np.diagonal(a[::-1,:], i)[::(2*(i % 2)-1)] for i in range(1-a.shape[0], a.shape[0])])
    mm = {e: i for i, e in enumerate(c_list)}
    matrix = np.array([[mm[e]+1 for e in l1] for l1 in a]) 
    return matrix


def create_zigzag_index6(rows, columns):

    matrix = np.array(range(rows * columns)).reshape(rows,columns) + 1

    solution=[[] for i in range(rows+columns-1)]

    for i in range(rows):
        for j in range(columns):
            sum=i+j
            if(sum%2 ==0):

                #add at beginning
                solution[sum].insert(0,matrix[i][j])
            else:

                #add at end of the list
                solution[sum].append(matrix[i][j])


    c_list = []
    for i in solution:
        for j in i:
            c_list.append(j)
    
    mm = {e: i for i, e in enumerate(c_list)}
    matrix2 = np.array([[mm[e]+1 for e in l1] for l1 in matrix]) 
    
    return matrix2

In [13]:
n = 4

In [14]:
create_zigzag_index(n)

array([[ 1.,  2.,  6.,  7.],
       [ 3.,  5.,  8., 14.],
       [ 4.,  9., 13., 18.],
       [10., 12., 19., 25.]])

In [15]:
create_zigzag_index2(n)

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12],
       [16, 15, 14, 13]])

In [16]:
create_zigzag_index3(n)

array([[ 1,  2,  4,  7],
       [ 3,  5,  8, 11],
       [ 6,  9, 12, 14],
       [10, 13, 15, 16]])

In [17]:
create_zigzag_index4(n)

array([[ 1,  2,  5,  3],
       [ 6,  9,  4,  7],
       [10, 13,  8, 11],
       [14, 12, 15, 16]])

In [18]:
create_zigzag_index5(n)

array([[ 1,  2,  6,  7],
       [ 3,  5,  8, 13],
       [ 4,  9, 12, 14],
       [10, 11, 15, 16]])

In [21]:
n = 4
m = 3

create_zigzag_index6(n, m)

array([[ 1,  2,  6],
       [ 3,  5,  7],
       [ 4,  8, 11],
       [ 9, 10, 12]])

In [23]:
for temp_txt in [txt, txt2]:
    print("temp_txt: ", temp_txt)
    for n in range(5, 13):
        print("n: ", n)
        sort_m = [
                  create_zigzag_index(n),
                  create_zigzag_index(n).T,
                  np.array(range(n**2)).reshape(n,n) + 1,
                  (np.array(range(n**2)).reshape(n,n) + 1).T,
                  create_zigzag_index2(n),
                  create_zigzag_index2(n).T,
                  create_zigzag_index3(n),
                  create_zigzag_index3(n).T,
                  create_zigzag_index4(n),
                  create_zigzag_index4(n).T,
                  create_zigzag_index5(n),
                  create_zigzag_index5(n).T,
                  create_zigzag_index6(n, n+1),
                  create_zigzag_index6(n, n+1).T,
                 ]
    
#         for m in sort_m:
#             print(m)
        for map_thai in [False]:
            for ban in ['WXYZ']:
                print(f"map_thai: {map_thai}, ban: {ban}")
                
                for x in sort_m:
                    m = zigzag_txt(temp_txt, x, map_thai = map_thai, ban = ban)
                
                    for include_blank in [False]:
#                         print(f"include_blank: {include_blank}")
                        s = to_word(m, include_blank=include_blank)
                        print("word sort:", s)
                        
#                         try:
#                             print("word decode:", base64.b64decode(s.encode('ascii')).decode()[::-1])
#                         except:
#                             print("word decode: -")
                print('\n')
        print('----------')
    print('xxxxxxxxx')

temp_txt:  CYtZBsWZaZliYZocWLZlXuZZYWYeYXZsXeZXtXWpXeRYYYd!ZnYeWXoYXasnX,WXWrWPoAdWesnciGenWr
n:  5
map_thai: False, ban: WXYZ
word sort: CsotBaLisll
word sort: CtlBailsLos
word sort: CtBsaliocLlu
word sort: CslciutLaBol
word sort: CtBasliolLcu
word sort: CllaiutLBsoc
word sort: CltBicsalLou
word sort: CtsoBaLuilcl
word sort: CstlicBaLuol
word sort: ClBasLltiuco
word sort: CtlBaisLlocu
word sort: CsotBcauiLll
word sort: CsoctBaLiulle
word sort: CtlBailsLuoec


----------
n:  6
map_thai: False, ban: WXYZ
word sort: CsoctBaLisellnep
word sort: CtlBailseLposcen
word sort: CtBsaliocLluese
word sort: ClstaocueeBlsiL
word sort: CtBsilaocLulees
word sort: CiltoueaceBlssL
word sort: ClctBiusaLeolse
word sort: CtsoBaliLlescue
word sort: CtaBolslciusLee
word sort: CoalsLetsiBlecu
word sort: CsoctBaLiellseu
word sort: CtlBailusLoesce
word sort: CsoctBeaLitlleuspe
word sort: CtlBailussLoecpete


----------
n:  7
map_thai: False, ban: WXYZ
word sort: CsocetBaLRiselln,epuene
word sort: CtluBailseLpe

All Zigzag index can't perform a sentence :(

# Method 2: WXYZ cursur

if WXYZ meaningless in word but it mean in cursur like

In [25]:
def next_step(i, j, c, symbols):
    new_i = i + symbols.get(c, {'i': 0})['i']
    new_j = j + symbols.get(c, {'j': 0})['j']
    if c in symbols.keys():
        c2 = ''
    else:
        c2 = c
    return new_i, new_j, c2

In [26]:
ass1 = {"W": {"i": -1, "j": 0},
        "X": {"i": 0, "j": -1},
        "Y": {"i": 1, "j": 0},
        "Z": {"i": 0, "j": 1}}

In [27]:
n = 10
m = np.array([['' for j in range(n)] for i in range(n)], dtype = 'object')

In [28]:
i = 2
j = 2

In [30]:
for c in txt:
    i, j, c2 = next_step(i, j, c, ass1)
    m[i, j] += c2

In [31]:
m

array([['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', 'CrCr', '', 'aa', 'lili', 'LuLu', 'll', '', ''],
       ['', '', 'tesnciGentesnciGen', 'BsBs', '', 'eReR', 'ocpocp', '',
        'ee', ''],
       ['', '', 'PoAdPoAd', '', '', '', '', 'etet', 'ss', ''],
       ['', '', 'rr', '', '', '', '', '', '', ''],
       ['', '', '', '', '', 'd!od!o', 'nn', '', '', ''],
       ['', '', '', ',,', 'asnasn', '', 'ee', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype=object)

In [32]:
from itertools import permutations 
perm = permutations(['W', 'X', 'Y', 'Z']) 

for p in list(perm):
    print(p)
    ass1 = {p[0]: {"i": -1, "j": 0},
            p[1]: {"i": 1, "j": 0},
            p[2]: {"i": 0, "j": 1},
            p[3]: {"i": 0, "j": -1}}
    
    n = 10
    m = np.array([['' for j in range(n)] for i in range(n)], dtype = 'object')
    i = 1
    j = 1
    
    for c in txt:
        i, j, c2 = next_step(i, j, c, ass1)
        m[i, j] += c2
#         m[i, j] += map_keyboard.get(c2, '')
    
    print(m)
    print(to_word(m, include_blank=False))
    print('')

('W', 'X', 'Y', 'Z')
[['a' '' '' '' '' '' '' '' 'us' 'lioc']
 ['' 'CBsr' 't' '' '' '' '' '' 'e' '']
 ['' 'esnciGen' '' '' '' '' '' 'tp' '' '']
 ['d!eo' 'PoAd' '' '' '' '' '' 'eR' '' 'n']
 ['' 'asnr' '' '' '' '' '' '' '' '']
 ['' ',' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' 'le' 'L']]
ausliocCBsrteesnciGentpd!eoPoAdeRnasnr,leL

('W', 'X', 'Z', 'Y')
[['' '' 'a' 'lioc' 'us' '' '' '' '' '']
 ['t' 'CBsr' '' '' 'e' '' '' '' '' '']
 ['' 'esnciGen' '' '' '' 'tp' '' '' '' '']
 ['' 'PoAd' 'd!eo' 'n' '' 'eR' '' '' '' '']
 ['' 'asnr' '' '' '' '' '' '' '' '']
 ['' ',' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '']
 ['' '' '' 'L' 'le' '' '' '' '' '']]
aliocustCBsreesnciGentpPoAdd!eoneRasnr,Lle

('W', 'Y', 'X', 'Z')
[['' '' '' '' '' '' '' '' '' '']
 ['' 'Cr' '' '' '' '' 'l' 'Lu' 'li' 'a']
 ['Bs' 'tesnciGen' '' '' '' '

All Cursur method can't perform a sentence :(

# Method 3: Easy Zigzag method

In [33]:
txt = "CYtZBsWZaZliYZocWLZlXuZZYWYeYXZsXeZXtXWpXeRYYYd!ZnYeWXoYXasnX,WXWrWPoAdWesnciGenWr"

In [34]:
txt5 = ''
txt6 = ''
for c in txt:
    txt5 = txt5 + c if c not in 'WXYZ' else txt5 + '_'
    txt6 = txt6 + c if c in 'WXYZ' else txt6 + '_'

print(txt)
print(txt5)
print(txt6)

CYtZBsWZaZliYZocWLZlXuZZYWYeYXZsXeZXtXWpXeRYYYd!ZnYeWXoYXasnX,WXWrWPoAdWesnciGenWr
C_t_Bs__a_li__oc_L_l_u_____e___s_e__t__p_eR___d!_n_e__o__asn_,___r_PoAd_esnciGen_r
_Y_Z__WZ_Z__YZ__W_Z_X_ZZYWY_YXZ_X_ZX_XW_X__YYY__Z_Y_WX_YX___X_WXW_W____W________W_


In [36]:
def zigzag_easy(txt, numRows):

    i = 0
    j = 0
    status = 'down'

    mat = np.array([[' ' for j in range(numRows)] for i in range(numRows)], dtype = 'object')

    for c in txt:
        mat[i, j] = c
        if status == 'down':
            if i+1 < mat.shape[0]:
                i = i + 1
            else:
                status = 'up'
                if j + 1 == mat.shape[1]:
                    mat = np.concatenate([mat, np.array([[' ' for k in range(numRows)]], dtype = 'object').T], axis = 1)
                i = i - 1
                j = j + 1
        elif status == 'up':
            if i != 0:
                if j + 1 == mat.shape[1]:
                    mat = np.concatenate([mat, np.array([[' ' for k in range(numRows)]], dtype = 'object').T], axis = 1)
                i = i - 1
                j = j + 1
            else:
                status = 'down'
                i = i + 1

    if mat[:, -1].sum().strip() == '':
        mat = mat[:, :-1].copy()

    return mat

In [37]:
temp_txt = txt
temp_txt

'CYtZBsWZaZliYZocWLZlXuZZYWYeYXZsXeZXtXWpXeRYYYd!ZnYeWXoYXasnX,WXWrWPoAdWesnciGenWr'

In [42]:
mat = zigzag_easy(temp_txt, numRows = 4)

pd.DataFrame(mat)

0  1  2  3  4  5  6  7  8  9   ... 30 31 32 33 34 35 36 37 38 39
0  C        W        Y        Z  ...  X        W        e        e
1  Y     s  Z     i  Z     L  l  ...  ,     r  P     W  s     G  n
2  t  B     a  l     o  W     X  ...  W  W     o  d     n  i     W
3  Z        Z        c        u  ...  X        A        c        r

[4 rows x 40 columns]

In [43]:
for e in mat.sum(axis = 1):
#     print(e)
    print(e.replace(' ', ''))

CWYZYZtRZoXWee
YsZiZLlZWXsXXeY!nXYn,rPWsGn
tBaloWXZYYXZWXYdYWXsWWodniW
ZZcueepYeaXAcr


Zigzag easy method can't perform a sentence too :(

# Method 4: Inverse Zigzag

But let's try some inverse

In [48]:
def zigzag_easy_inverse(s, numRows):
    
    mat = zigzag_easy(s, numRows = numRows)

    i = 1
    l2 = []
    for l in mat:
        l1 = []
        for c in l:
            if c != ' ':
                l1.append(i)
                i = i + 1
            else:
                l1.append(' ')
        l2.append(l1)

    mat2 = np.array(l2)
    
    mat3 = zigzag_txt(s, mat2, map_thai = False, ban = '')

    i = 0
    j = 0
    c = mat3[i, j]
    status = 'down'

    s2 = ""

    while c != ' ':
        s2 += c
        if status == 'down':
            if i+1 < mat3.shape[0]:
                i = i + 1
            else:
                status = 'up'
                i = i - 1
                j = j + 1
        elif status == 'up':
            if i != 0:
                i = i - 1
                j = j + 1
            else:
                status = 'down'
                i = i + 1
            
        if j == mat3.shape[1]: break

        c = mat3[i, j]
    
    return s2

In [51]:
for numRows in range(2, 10):
    print(f"{numRows}: {zigzag_easy_inverse(txt, numRows)}")

2: CeYRtYZYBYsdW!ZZanZYleiWYXZooYcXWaLsZnlXX,uWZXZWYrWWYPeoYAXdZWseXsenZcXitGXeWnpWXr
3: CuWZYZXYtWWYZerYBXWZssPXWeoZZXAtaXdWZpWXleeRiYsYYYndZ!cZoniYceGWWXeoLYnXZaWslnrXX,
4: CoeoRcYWYAYLtZYddlZX!WZuBZneYZsYesWWWYXnoeZYYcXXaZaissZXnGXelZ,eWXitXnWXYWrWWpZXPr
5: CiXWeXeYYZZosYXotctXnaXWZLWscnpZBlXXi,eXsuRWGXYZWZYWerYYZWdWnP!YaeZoWAnYZXYdrWeZls
6: CZYRsnnYelYiYYXc,YXYtZZdWiX!soZcXZWGrneWBLZYWePeXZsltWonAXXXWuWodWWYpZZZXXersaeYaW
7: CZXe!,cWZZuaYZZXnXiWYtZltiYXerGWWWWYZZYpXPeooXeoBcYeYAndXRXWsLZYaWWesYsZWlXYnsrnXd
8: CWLYXWWirXeXZZYalZRoWGPYYsXZtluXYXoeAaYeZiZYZZdsdnWn!XYZBoWtZXeWs,nXYcsWeWYWnrcXep
9: CWLeX!aPGosZWYZZYalXpnnAedXYXZXZtlusee,WneWWRXZiZYZeYXXsWnWoYZYZBoWXYYrcriWXdtYcsW


If we ignore "WXYZ" ?

In [52]:
for numRows in range(2, 10):
    print(f"{numRows}: {zigzag_easy_inverse(txt2, numRows)}")

2: CnteBosaaslni,orcPLolAudeessentcpieGRedn!r
3: CudetseeBtspsenRadc!lnieioGaosenc,nrLProlA
4: ConnectLocalBusiness,GreatPeopleAndRiders!
5: Cie,irRotcdPGo!LBlnAedeuseoensasaesnrcntlp
6: CleeoGAotitopadeesecBLRnsnn,dlsu!rcriPneas
7: CauRsdeendeltis!,snnrneoBctePcrioopLsleaAG
8: CsLtn,eesreplatlueoPnncoaReiBosdsAirGdn!ec
9: CscsRoreesPadeLatllt!sonncAnnpuiBoeee,dirG


Finally!!!, sentense zigzag_easy_inverse(txt2, numRows = 4) can read!!! :)